<?php
/**
 * Library Used: https://github.com/irazasyed/telegram-bot-sdk
 * Reference Code: https://telegram-bot-sdk.readme.io/reference
 */
// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit3284b02d92269b76970db3b8d3305184::getLoader();
